name: cpgtransformer2
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - absl-py=1.1.0
  - aiohttp=3.8.1
  - aiosignal=1.2.0
  - async-timeout=4.0.2
  - attrs=21.4.0
  - blas=1.0
  - blinker=1.4
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.6.15
  - cachetools=5.0.0
  - certifi=2022.6.15
  - cffi=1.14.6
  - charset-normalizer=2.1.0
  - click=8.1.3
  - colorama=0.4.5
  - cryptography=37.0.2
  - cudatoolkit=11.3.1
  - ffmpeg=4.3
  - freetype=2.10.4
  - frozenlist=1.3.0
  - fsspec=2022.5.0
  - future=0.18.2
  - gmp=6.2.1
  - gnutls=3.6.13
  - google-auth=2.9.1
  - google-auth-oauthlib=0.4.6
  - grpcio=1.38.1
  - idna=3.3
  - importlib-metadata=4.11.4
  - intel-openmp=2021.4.0
  - jpeg=9e
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libiconv=1.17
  - libpng=1.6.37
  - libprotobuf=3.18.0
  - libstdcxx-ng=11.2.0
  - libtiff=4.2.0
  - libuv=1.40.0
  - libwebp-base=1.2.2
  - lz4-c=1.9.3
  - markdown=3.4.1
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - multidict=6.0.2
  - ncurses=6.3
  - nettle=3.6
  - numpy=1.22.3
  - numpy-base=1.22.3
  - oauthlib=3.2.0
  - olefile=0.46
  - openh264=2.1.1
  - openssl=1.1.1o
  - packaging=21.3
  - pillow=7.2.0
  - pip=22.1.2
  - protobuf=3.18.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.21
  - pydeprecate=0.3.1
  - pyjwt=2.4.0
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - python=3.9.12
  - python_abi=3.9
  - pytorch=1.10.1
  - pytorch-lightning=1.5.0
  - pytorch-mutex=1.0
  - pyu2f=0.1.5
  - pyyaml=6.0
  - readline=8.1.2
  - requests=2.28.1
  - requests-oauthlib=1.3.1
  - rsa=4.9
  - six=1.16.0
  - sqlite=3.38.5
  - tensorboard=2.9.1
  - tensorboard-data-server=0.6.0
  - tensorboard-plugin-wit=1.8.1
  - tk=8.6.12
  - torchaudio=0.10.1
  - torchvision=0.11.2
  - tqdm=4.64.0
  - typing-extensions=4.3.0
  - typing_extensions=4.3.0
  - tzdata=2022a
  - urllib3=1.26.10
  - werkzeug=2.1.2
  - wheel=0.37.1
  - xz=5.2.5
  - yaml=0.2.5
  - yarl=1.7.2
  - zipp=3.8.0
  - zlib=1.2.12
  - zstd=1.4.9
  - pip:
    - pandas==1.4.3
    - python-dateutil==2.8.2
    - pytz==2022.1
    - setuptools==59.5.0
    - torchmetrics==0.6.0
